### ISSUE TITLE
Factories get automatically loaded when rails environment is loaded - which should be optional

### ISSUE THREAD

**Issue by oveddan** [thoughtbot/factory_girl_rails#134]
When an application is started up, and factory_girls_rails is included, it automatically loads the factories.  This can become a problem if some of the classes the factory is attempting to load are not ready to be loaded yet.

For example, we have some classes that leverage the column_names method of ActiveRecord to generate some other methods.  If the schema migration has not been run yet, when factory_girl_rails gets loaded, this breaks as the column_names it's looking for do not yet exist yet on the model.  

This error happens in the [railtie](https://github.com/thoughtbot/factory_girl_rails/blob/master/lib/factory_girl_rails/railtie.rb), at line 21 (FactoryGirl.find_definitions):

```ruby
    config.after_initialize do
      FactoryGirl.find_definitions

      if defined?(Spring)
        Spring.after_fork { FactoryGirl.reload }
      end
    end
```

There should be an option to opt out of invoking FactoryGirl.find_definitions here, and instead we should be able to call this method when we need to, such as in the files that load up our test suites (spec_helper.rb for example).

**Comment by chrishough** [comment]
We just ran into this same issue in our application... and now we have to figure out if the only solution is removing `factory_girl_rails ` in favor of `factory_girl`

**Comment by singpolyma** [comment]
Just ran into this.  Using the name of a model class in a factory (without wrapping in `{}`) causes `db:schema:load` to crash

**Comment by gaggle** [comment]
Just ran into this, I get an error doing standard Rake operations or even `rails s` relating to FactoryGirl being unable to load a required file. This is a support file I load from the top of a factory file, as far as I can tell the import error occurs because none of the `spec` folders are available to load from. Which actually makes sense, because I'm not running a test.

I don't understand why FactoryGirl is doing anything at all in this case, as I see it it should only be part of my stack when I invoke `rake spec` or `rspec` commands. In all other cases it should stay away, just like I wouldn't expect to get errors from *spec files unless specifically running tests.

I've solved this by switching to the `factory_girl` gem and doing my own initialisation in `spec_helper.rb`, as outlined by @tobypinder two years ago. If this gem adopts a more aggressive non-interference policy I'll be happy to provide feedback as to whether it fixes our problem. FYI the change from #211 did not fix this problem.

**Comment by nbulaj** [comment]
The same problem here https://github.com/doorkeeper-gem/doorkeeper/issues/1043.

Doorkeeper gem lazy loads ActiveRecord models with ActiveSupport `on_load` hook for `:active_record`. But because of no `ActiveRecord::Base` calls at the moment of factories load, `factory_bot_rails``after_initializaer` tries to find definitions and raises an error with No Class Defined.
